---
name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels: ["enhancement", "triage", "needs-triage"]
assignees: githubusernameassignee

body:
  - type: markdown
    attributes:
      value: |
        Got an idea to make this better? We'd love to hear it! Tell us what you need and we'll see how we can help.

  - type: textarea
    id: problem
    attributes:
      label: What problem would this solve?
      description: What's making your work difficult right now?
      placeholder: "Example: When I'm analyzing data, I have to manually export each chart one by one, which takes forever..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe your ideal solution - don't worry about technical details!
      placeholder: "Example: A 'Download All Charts' button that saves everything as a ZIP file"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: How important is this for your work?
      options:
        - "Would be nice to have"
        - "Would help me work more efficiently"
        - "I really need this to do my job"
        - "This is blocking my research"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Tell us more
      description: Any additional details, mockups, or examples that might help us understand what you need?
      placeholder: "Screenshots of similar features, links to examples, or any other context that helps explain your idea"

  - type: dropdown
    id: user-type
    attributes:
      label: I am a...
      options:
        - "Researcher"
        - "PhD student"
        - "Post-doc"
        - "Research assistant"
        - "Administrative staff"
        - "Other"
