name: Quality Checks

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

jobs:
  quality:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4.4.0
        with:
          node-version: ">=22.0.0 < 23.0.0"
          cache: "npm"
          cache-dependency-path: "./npm-shrinkwrap.json"

      - name: Install dependencies
        run: npm ci --ignore-scripts

      - name: Run prettier
        run: npx prettier --check .

      # - name: Run ESLint
      #   run: npm run lint

      # - name: Check formatting
      #   run: npm run format -- --check

      # - name: Type check
      #   run: npm run convert && npx quasar prepare && npm run type-check

      # - name: Run tests
      #   run: npm test
